---
- name: "go get some packages"
  shell: "source ~/.zshenv && go get -u github.com/{{item}}"
  args:
    chdir: "/home/{{user_name}}/"
  sudo: "yes"
  sudo_user: "{{user_name}}"
  with_items:
    - "c9s/gomon"
    - "codegangsta/gin"