---
system_packages:
  - "curl"
  - "htop"
  - "nethogs"
  - "iotop"
  - "powertop"
  - "glances"
  - "git"
  - "vim"
  - "sudo"
  # `mkpasswd` bin
  - "debian-whois-mkpasswd"
  - "zsh"
  - "oh-my-zsh-git"
  - "downgrade"
  - "autojump"
  - "udiskie"
  - "avahi"
  - "xbindkeys"
  - "tlp"
  - "acpi"
  - "acpid"
  - "tp_smapi"
  - "acpi_call"
  - "xorg-xbacklight"
  - "xorg-xsetroot"
  - "alsa-utils"
  - "alsa-plugins"
  - "redshift-minimal"
  - "volnoti"
  - "keychain"
  - "rsync"
  - "xf86-input-synaptics"
  - "xf86-video-intel"
  - "refind-efi"
  - "ntp"
  - "roxterm"
  - "ansible"
  - "libnotify"
  - "ethtool"
  - "smartmontools"
  - "polkit"
  - "strace"
  - "dhclient"
compression_packages:
  - "xarchiver"
  - "p7zip"
  - "zip"
  - "unzip"
  - "unrar"
virtualization_packages:
  - "virtualbox"
  - "virtualbox-ext-oracle"
  - "virtualbox-host-modules"
  - "virtualbox-guest-iso"
  - "packer-io"
  - "docker"
  - "vagrant"
  - "net-tools"
office_packages:
  - "dropbox"
  - "simple-scan"
  - "google-chrome-beta"
  - "arandr"
  - "kingsoft-office"
  - "clipit"
  - "vlc"
  - "spotify"
  - "hplip"
  # brother scan driver
  - "brscan4"
  - "gnome-calculator"
  - "transmission-gtk"
  - "geeqie"
  - "evince"
  - "libreoffice-writer"
  - "todotxt"
  - "jpegoptim"
file_manager_packages:
  - "thunar"
  - "gvfs"
  - "gvfs-smb"
  - "polkit-gnome"
  - "xfce4-panel"
  - "tumbler"
  - "thunar-volman"
  - "thunar-archive-plugin"
  - "thunar-media-tags-plugin"
  - "thunar-dropbox"
  - "thunar-shares-plugin"
  - "thunar-vcs-plugin"
wm_packages:
  # https://wiki.archlinux.org/index.php/Xorg#Installation
  - "xorg-server"
  - "xorg-xinit"
  - "x11-ssh-askpass"
  - "i3-wm"
  - "j4-dmenu-desktop"
  - "i3lock"
  - "i3status"
  - "dex"
  - "dunst"
  - "mediterraneannight-theme"
  - "faenza-icon-theme"
  - "lxappearance"
  - "xorg-xmodmap"
  - "xorg-xdpyinfo"
  - "scrot"
# theses fonts will provide you good fonts on your whole system
fonts_packages:
  # programming font
  - "otf-inconsolatazi4-ibx"
  - "artwiz-fonts"
  - "font-bh-ttf"
  - "font-bitstream-speedo"
  - "sdl_ttf"
  - "ttf-bitstream-vera"
  - "ttf-cheapskate"
  - "ttf-ms-fonts"
  - "ttf-vista-fonts"
  # - "infinality-bundle"
  - "freetype2-infinality-ultimate"
  - "fontconfig-infinality-ultimate"
  - "cairo-infinality-ultimate"
  - "ttf-droid-ib"
  - "ttf-opensans-ib"
  - "ttf-ubuntu-font-family-ib"
  # - "infinality-bundle-fonts # https://wiki.archlinux.org/index.php/Infinality-bundle+fonts"
  - "ibfonts-meta-base"
  - "ibfonts-meta-extended"
  - "otf-brill"
  - "otf-neris"
  - "ttf-aller"
  - "ttf-envy-code-r"
dev_packages:
  - "sublime-text-nightly"
  - "go"
  - "git-cola"
  - "jre8-openjdk-headless"
fun_packages: # @neoziro made me install this
  - "steam"
  - "steam-fonts"
  - "lib32-intel-dri"
printing_packages:
  - "cups"
  - "hplip"
  - "python2-dbus"
  - "ghostscript"