---
- name: add archlinuxfr repository to pacman
  lineinfile:
    dest: /etc/pacman.conf
    state: present
    line: "{{ item }}"
  with_items:
    - '[archlinuxfr]'
    - 'SigLevel = Never'
    - 'Server = http://repo.archlinux.fr/$arch'
- name: install yaourt
  pacman:
    name: yaourt
    state: present
