---
- name: "install some handy npm packages"
  npm:
    name: "{{item}}"
    global: "yes"
    state: "present"
    executable: "/home/{{user_name}}/.nvm/current/bin/npm"
  sudo: true
  sudo_user: "{{user_name}}"
  environment:
    PYTHON: "/bin/python2"
  with_items:
    - "http-server"
    - "wifi.sh"
    - "selenium-standalone"
    - "bower"
    - "mversion"
    - "david"
    - "webkit-devtools-agent"
    - "gh"
    - "zuul"
    - "mocha"
    - "prova"
    - "grunt-cli"
    - "browserify"
    - "uglify-js"
    - "duo"
    - "component"
    - "watchify"
    - "localtunnel"
    - "eslint"
    - "testling"
    - "gulp"
  tags:
    - "debug"
